config/routes.rb
MDme::Application.routes.draw do
  require 'domains'

  match '/', to: 'doctors#signin', via: 'get', constraints: { subdomain: 'doctors' }

  match '/',     to: 'admins#signin', via: 'get',    constraints: { subdomain: 'admin' }
  match '/', to: 'static_pages#home', via: 'get'
  root 'static_pages#home', constraints: { subdomain: 'www' }

  match '/help',            to: 'static_pages#help',     via: 'get'#,    constraints: { subdomain: 'www' }
  match '/about',           to: 'static_pages#about',    via: 'get'#,    constraints: { subdomain: 'www' }
  match '/contact',         to: 'static_pages#contact',  via: 'get'#,    constraints: { subdomain: 'www' }
  match '/signin',          to: 'sessions#new',          via: 'get'#,    constraints: { subdomain: 'www' }
  match '/signout',         to: 'sessions#destroy',      via: 'delete'
  match '/forgot_password', to: 'password_reset#new',    via: 'get',    as: :forgot_password
  match '/forgot_password', to: 'password_reset#create', via: 'post',   as: :password_reset

  post '/submit-comment'                                 => 'static_pages#submit_comment',             as: :contact_comment_path
  post 'appointments/check-in'                           => 'admins/appointments#check-in',            as: :admin_appointment_check_in
  get  'patients/:patiend_id/appointments/browse'        => 'patients/appointments#open_appointments', as: :open_appointments_browse
  get  'patients/:patient_id/appointments/requests'      => 'patients/appointments#open_requests',     as: :open_requests

  get  'admins/:admin_id/doctors/search'                 => 'admins/doctors#search',                   as: :admin_doctors_search
  get  'admins/:admin_id/patients/search'                => 'admins/patients#search',                  as: :admin_patient_search
  get  'admins/:admin_id/patients/browse'                => 'admins/patients#browse',                  as: :admin_patients_browse
  get  'admins/:admin_id/patients/:id/registration-form' => 'admins/patients#registration_form',       as: :admin_patient_registration_form
  get  'admins/:admin_id/appointments/browse'            => 'admins/appointments#browse',              as: :admin_appointments_browse
  get  'admins/:admin_id/appointments/ajax-browse'       => 'admins/appointments#ajax_browse',         as: :appointments_ajax_browse
  get  'admins/:admin_id/appointments/new/browse'        => 'admins/appointments#new_browse',          as: :admin_open_appointments_browse
  post 'admins/:admin_id/appointments/notify_ready'      => 'admins/appointments#notify_ready',        as: :notify_appointment_ready
  get  'admins/:admin_id/doctors/opentimes'              => 'admins/doctors#open_times',               as: :admin_doctors_opentimes
  get  'patients/:admin_id/doctors/opentimes'            => 'patients/appointments#open_times',        as: :patients_doctors_opentimes
  get  'doctors/opentimes'                               => 'doctors#open_appointments',               as: :doctor_open_appointments
  get  'doctors/:id/public'                              => 'doctors#show_public',                     as: :doctor_public_show
  get  'doctors/:id/changepassword'                      => 'doctors#change_password',                 as: :doctor_password
  post 'doctors/:id/updatepassword'                      => 'doctors#update_password',                 as: :doctor_update_password

  get 'clinics/:id/checkin/:patient_id'                  => 'clinics#checkin',                         as: :clinic_checkin

  get 'appointments/:id/fill_appointment'                => 'appointments#fill_appointment',           as: :fill_appointment

  resources :sessions, only: [:new, :create, :destroy]
  resources :admins, only: [:index]
  resources :doctors, except: [:new, :create, :destroy]

  resources :doctors do
    resources :appointments, only: [:index, :show], controller: 'doctors/appointments'
    resources :patients,     only: [:index, :show], controller: 'doctors/patients'
  end

  resources :patients do
    resources :appointments, controller: 'patients/appointments' do
      collection do
        get :home
      end
    end
    resources :doctors, only: [:index, :show], controller: 'patients/doctors'
    resources :clinics, only: [:index, :show], controller: 'patients/clinics' do
      collection do
        post :open_times
        get :get_doctors
      end
      member do
        get :display
      end
    end
    resources :devices, only: [:create],       controller: 'patients/devices'
    member do
      get   :change_password
      patch :update_password
    end
    collection do
      get :get_upcoming_appointment
    end
  end

  resources :clinics do
    resources :doctors, only: [:index], controller: 'clinics/doctors'
  end
  
  resources :admins do
    resources :departments,  controller: 'admins/departments'
    resources :patients,     controller: 'admins/patients'
    resources :doctors,      controller: 'admins/doctors'
    resources :appointments, controller: 'admins/appointments' do
      collection do
        get  :approval
        get  :show_on_date
        get  :manage_delays
      end
      member do
        post :approve_deny
        post :add_delay
      end
    end
    resources :clinics,      controller: 'admins/clinics'  do
      collection do
        post :open_times
      end
    end
  end

  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
      resources :patients, controller: 'patients', only: [:index]
      get 'patients/show' => 'patients#show', as: 'patient_profile'
      put 'patients/update' => 'patients#update', as: 'patient_update_profile'

      namespace :patients do
        get 'appointments/confirmed' => 'appointments#confirmed_appointments', as: 'confirmed_appointments'
        get 'appointments/requested' => 'appointments#requested_appointments', as: 'requested_appointments'
        resources :doctors, controller: 'doctors', only: [:index, :show]
        resources :appointments, controller: 'appointments', only: [:create, :update, :show, :index]
        resources :clinics, controller: 'clinics', only: [:index, :show]
        resources :devices, controller: 'devices', only: [:create]
        get 'departments' => 'doctors#department_index', as: 'doctors_departments'

      end
    end
    namespace :mobile do
      get  'patients/:patient_id/upcoming-appointment-qrcode'=> 'patients#upcoming_appointment_qrcode',     as: :upcoming_appointment_qrcode
      post 'login' => 'sessions#create'
      delete 'sessions' => 'sessions#destroy'
      get  'patients/get-upcoming-appointment' => 'patients#get_upcoming_appointment'
      resources :patients, controller: 'patients', only: [:show, :edit, :update, :destroy]
      namespace :patients do
        resources :devices, controller: 'devices', only: [:create]
      end
    end
  end

  

end

app/controllers/static_pages_controller.rb
# MDme Rails master application
# Author:: Matt Hamada (maito:mattahamada@gmail.com)
# 10/28/13
# Copyright:: Copyright (c) 2014 MDme
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential.

# +StaticPagesController+ main pages when not signed in
class StaticPagesController < ApplicationController
  # TODO patients should probably still be able to see home page
  # GET www.mdme.us
  def home
    # if patient_signed_in?
    #   redirect_to patient_path(current_patient)
    # end
    render 'sessions/new' unless patient_signed_in?
  end

  # GET www.mdme.us/help
  def help; end

  # GET www.mdme.us/about
  def about
    @active = :about
    return render 'sessions/new' unless patient_signed_in?
  end

  # GET www.mdme.us/contact
  def contact
    @active = :contact
    return render 'sessions/new' unless patient_signed_in?
  end

  def find_patient

  end


  #post www.mdme.us/submit-comment
  def submit_comment
    begin
      name = params[:client][:name]
      email = params[:client][:email]
      phone = params[:client][:phone]
      comment = params[:client][:comment]
      SubmitCommentMailer.send_email(name, email, phone, comment).deliver_later
      @message = 'Message submitted'
      respond_to do |format|
        format.json do
          render json: {
                     status: true
                 }
        end
        format.js do
          @status = :success;
        end
        format.html do
          flash[:success] = @message
          redirect_to contact_path
        end
      end

    rescue => error
      @message = 'An error occurred.  Please try again later'
      respond_to do |format|
        format.json do
          render json: {
                     status: false,
                     message: $!.message
                 }
        end
        format.js do
          @status = :danger
        end
        format.html do
          flash[:danger] = message
          redirect_to contact_path
        end
      end
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_header.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <div class="breadcrumbs">
        <%= render_breadcrumbs  separator: ' > ' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3" style="text-align: center;">
      <%= link_to image_tag(asset_path('full_logo_white.png'), class: 'logo img-responsive'), '#/' %>

    </div>
  </div>
  <%= render 'static_pages/menu_black' %>

app/views/static_pages/_menu_black.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <hr id="menu-topbar-black"/>
  </div>
</div>
<div class="row" style="margin-bottom: 9em;">
  <div class="col-md-8 col-md-offset-2">
    <div class="row home-menu-links">
      <div class="col-xs-3 col-md-3 <%= 'top-links-active' if @active == :about %>">
      <%= link_to 'ABOUT', "#/about" %>
    </div>
    <div class="col-xs-3 col-md-3 <%= 'top-links-active' if @active == :services %>">
      <a href="#/services">SERVICES</a>
    </div>
    <div class="col-xs-3 col-md-3 <%= 'top-links-active' if @active == :contact %>">
      <%= link_to 'CONTACT', '#/contact' %>
    </div>
    <div class="col-xs-3 col-md-3 <%= 'top-links-active' if @active == :signin %>">
      <%= link_to 'SIGN IN', '#/signin' %>
    </div>
  </div>
  </div>
</div>

app/views/static_pages/_menu_white.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <hr id="menu-topbar-black"/>
  </div>
</div>
<div class="row" style="margin-bottom: 9em;">
  <div class="col-md-8 col-md-offset-2">
    <div class="row home-menu-links">
      <div class="col-md-4">
        <%= link_to 'SIGN IN', signin_path %>
      </div>
      <div class="col-md-4">
        <a href="#">SERVICES</a>
      </div>
      <div class="col-md-4">
        <a href="#">CONTACT</a>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_static_pages_menu.html.erb
<div id="static-pages-menu">
  <div class="container-fluid">
    <div class="row">
      <div class="static-pages-menu-links">
        <div class="col-sm-3">
          <%= link_to 'home', root_path %>
        </div>
        <div class="col-sm-3">
          <a href="#/about">about</a>
        </div>
        <div class="col-sm-3">
          <%= link_to 'contact', contact_path %>
        </div>
        <% if @current_patient.nil? %>
          <div class="col-sm-3">
            <%= link_to 'sign in', signin_path %>
          </div>
        <% else %>
          <div class="col-sm-3">
            <%= link_to 'my account', @current_patient %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <% debug(params) if Rails.env.development? %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<%= render 'static_pages/header' %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<div class="row-fluid">
  <div class="col-sm-6" style="text-align: center;">
    <div class="row">
      <div class="col-sm-12">
        <%= image_tag "contact-image.png", id: 'contact-logo', class: 'img-responsive center-block ' %>
      </div>
    </div>
    <div class="row">
      <div class="12" style="text-align: center;">
        55 Fruit Street<br/>
        Boston, Ma 02114<br/><br/>
        Telephone: 617-724-7285<br/>
        Email: foo@bar.com
      </div>
    </div>
  </div>
  <div class="col-sm-4" style="text-align: center;">
    <h4 style="text-decoration: underline; text-align: center;">EMAIL US</h4> <br/><br/>
    <div class="message"></div>
    <%= form_tag url_for(controller:'static_pages', action:'submit_comment'), method: 'POST', remote: true do %>
      <fieldset class="form-group">
        <%= label_tag 'client[name]', '', class:'sr-only'%>
        <%= text_field_tag 'client[:name]', '', class: 'form-control', placeholder:'name', required: true %>
      </fieldset>
      <fieldset class="form-group">
        <%= label_tag 'client[email]', '', class:'sr-only'%>
        <%= email_field_tag 'client[:email]', '', class:'form-control', placeholder: 'email', required: true %>
      </fieldset>
      <fieldset class="form-group">
        <%= label_tag 'client[telephone]', '', class:'sr-only'%>
        <%= text_field_tag 'client[:telephone]', '', class: 'form-control', placeholder: 'Phone', type:'tel' %>
      </fieldset>
      <fieldset class="form-group">
        <%= label_tag 'client[comment]', '', class:'sr-only'%>
        <%= text_area_tag 'client[:name]', '', class:'form-control', rows: 4, style:'text-align: left; display: block; margin-left: auto; margin-right: auto;', placeholder:'Comments', required: true %>
      </fieldset>
      <div style="text-align: center; margin-top: 2em;">
        <%= submit_tag 'Submit', class:'btn btn-medium btn-primary', id:'contact-submit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/help.html.erb
<%= render 'static_pages/header' %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<%#<div ui-view class="container-fluid" id="static-wrapper"></div> %>
<div class="container-black-logo">
  <div class="row-fluid">
    <div class="col-sm-6 col-sm-offset-3" style="text-align: center">
      <h4 style="margin-top: 2em;">
        scheduling simplified
      </h4>
    </div>
  </div>
  <div class="row-fluid">
    <div class="col-sm-12 " style="text-align: center; margin-top: 2em;">
      <%= link_to 'Learn More', about_path, class: 'btn btn-primary', role: 'button' %>
    </div>
  </div>
</div>

app/views/static_pages/submit_comment.js.erb
$('.message').html('<div class="alert alert-<%= @status.to_s %>"><%= @message %></div>');
<% if @status == :success %>
  $('form')[0].reset();
<% end %>