config/routes.rb
MDme::Application.routes.draw do
  require 'domains'

  match '/', to: 'doctors#signin', via: 'get', constraints: { subdomain: 'doctors' }

  match '/',     to: 'admins#signin', via: 'get',    constraints: { subdomain: 'admin' }
  match '/', to: 'static_pages#home', via: 'get'
  root 'static_pages#home', constraints: { subdomain: 'www' }

  match '/help',            to: 'static_pages#help',     via: 'get'#,    constraints: { subdomain: 'www' }
  match '/about',           to: 'static_pages#about',    via: 'get'#,    constraints: { subdomain: 'www' }
  match '/contact',         to: 'static_pages#contact',  via: 'get'#,    constraints: { subdomain: 'www' }
  match '/signin',          to: 'sessions#new',          via: 'get'#,    constraints: { subdomain: 'www' }
  match '/signout',         to: 'sessions#destroy',      via: 'delete'
  match '/forgot_password', to: 'password_reset#new',    via: 'get',    as: :forgot_password
  match '/forgot_password', to: 'password_reset#create', via: 'post',   as: :password_reset

  post '/submit-comment'                                 => 'static_pages#submit_comment',             as: :contact_comment_path
  post 'appointments/check-in'                           => 'admins/appointments#check-in',            as: :admin_appointment_check_in
  get  'patients/:patiend_id/appointments/browse'        => 'patients/appointments#open_appointments', as: :open_appointments_browse
  get  'patients/:patient_id/appointments/requests'      => 'patients/appointments#open_requests',     as: :open_requests

  get  'admins/:admin_id/doctors/search'                 => 'admins/doctors#search',                   as: :admin_doctors_search
  get  'admins/:admin_id/patients/search'                => 'admins/patients#search',                  as: :admin_patient_search
  get  'admins/:admin_id/patients/browse'                => 'admins/patients#browse',                  as: :admin_patients_browse
  get  'admins/:admin_id/patients/:id/registration-form' => 'admins/patients#registration_form',       as: :admin_patient_registration_form
  get  'admins/:admin_id/appointments/browse'            => 'admins/appointments#browse',              as: :admin_appointments_browse
  get  'admins/:admin_id/appointments/ajax-browse'       => 'admins/appointments#ajax_browse',         as: :appointments_ajax_browse
  get  'admins/:admin_id/appointments/new/browse'        => 'admins/appointments#new_browse',          as: :admin_open_appointments_browse
  post 'admins/:admin_id/appointments/notify_ready'      => 'admins/appointments#notify_ready',        as: :notify_appointment_ready
  get  'admins/:admin_id/doctors/opentimes'              => 'admins/doctors#open_times',               as: :admin_doctors_opentimes
  get  'patients/:admin_id/doctors/opentimes'            => 'patients/appointments#open_times',        as: :patients_doctors_opentimes
  get  'doctors/opentimes'                               => 'doctors#open_appointments',               as: :doctor_open_appointments
  get  'doctors/:id/public'                              => 'doctors#show_public',                     as: :doctor_public_show
  get  'doctors/:id/changepassword'                      => 'doctors#change_password',                 as: :doctor_password
  post 'doctors/:id/updatepassword'                      => 'doctors#update_password',                 as: :doctor_update_password

  get 'clinics/:id/checkin/:patient_id'                  => 'clinics#checkin',                         as: :clinic_checkin

  get 'appointments/:id/fill_appointment'                => 'appointments#fill_appointment',           as: :fill_appointment

  resources :sessions, only: [:new, :create, :destroy]
  resources :admins, only: [:index]
  resources :doctors, except: [:new, :create, :destroy]

  resources :doctors do
    resources :appointments, only: [:index, :show], controller: 'doctors/appointments'
    resources :patients,     only: [:index, :show], controller: 'doctors/patients'
  end

  resources :patients do
    resources :appointments, controller: 'patients/appointments' do
      collection do
        get :home
      end
    end
    resources :doctors, only: [:index, :show], controller: 'patients/doctors'
    resources :clinics, only: [:index, :show], controller: 'patients/clinics' do
      collection do
        post :open_times
        get :get_doctors
      end
      member do
        get :display
      end
    end
    resources :devices, only: [:create],       controller: 'patients/devices'
    member do
      get   :change_password
      patch :update_password
    end
    collection do
      get :get_upcoming_appointment
    end
  end

  resources :clinics do
    resources :doctors, only: [:index], controller: 'clinics/doctors'
  end
  
  resources :admins do
    resources :departments,  controller: 'admins/departments'
    resources :patients,     controller: 'admins/patients'
    resources :doctors,      controller: 'admins/doctors'
    resources :appointments, controller: 'admins/appointments' do
      collection do
        get  :approval
        get  :show_on_date
        get  :manage_delays
      end
      member do
        post :approve_deny
        post :add_delay
      end
    end
    resources :clinics,      controller: 'admins/clinics'  do
      collection do
        post :open_times
      end
    end
  end

  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
      resources :patients, controller: 'patients', only: [:index]
      get 'patients/show' => 'patients#show', as: 'patient_profile'
      put 'patients/update' => 'patients#update', as: 'patient_update_profile'

      namespace :patients do
        get 'appointments/confirmed' => 'appointments#confirmed_appointments', as: 'confirmed_appointments'
        get 'appointments/requested' => 'appointments#requested_appointments', as: 'requested_appointments'
        resources :doctors, controller: 'doctors', only: [:index, :show]
        resources :appointments, controller: 'appointments', only: [:create, :update, :show, :index]
        resources :clinics, controller: 'clinics', only: [:index, :show]
        resources :devices, controller: 'devices', only: [:create]
        get 'departments' => 'doctors#department_index', as: 'doctors_departments'

      end
    end
    namespace :mobile do
      get  'patients/:patient_id/upcoming-appointment-qrcode'=> 'patients#upcoming_appointment_qrcode',     as: :upcoming_appointment_qrcode
      post 'login' => 'sessions#create'
      delete 'sessions' => 'sessions#destroy'
      get  'patients/get-upcoming-appointment' => 'patients#get_upcoming_appointment'
      resources :patients, controller: 'patients', only: [:show, :edit, :update, :destroy]
      namespace :patients do
        resources :devices, controller: 'devices', only: [:create]
      end
    end
  end

  

end

app/views/admins/_header.html.erb
<nav class="admin-navbar navbar navbar-dark navbar-static-top bg-invers ">
  <button type="button" class="navbar-toggler hidden-md-up" data-toggle="collapse" data-target="#admin-nav" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    &#9776;
  </button>
  <%= link_to "MDme |", admin_appointments_path(@admin), :class=>'navbar-brand' %>
  <nav class="nav navbar-nav collapse pull-sm-left navbar-toggleable-sm" id="admin-nav" style="font-size: .8rem;">
    <%= link_to "<i class='icon-book mdme-icon'></i> Appointments".html_safe, admin_appointments_path(current_admin), :class=>"nav-item nav-link admin-header-nav-link" %>
    <%= link_to "<i class='icon-doctor mdme-icon'></i> Doctors".html_safe, admin_doctors_path(current_admin), :class=>"nav-item nav-link admin-header-nav-link" %>
    <%= link_to "<i class='icon-man mdme-icon'></i> Patients".html_safe, admin_patients_path(current_admin), :class=>"nav-item nav-link admin-header-nav-link" %>
    <%= link_to "<i class='icon-hospital mdme-icon'></i> Clinic".html_safe, admin_departments_path(current_admin), :class=>"nav-item nav-link admin-header-nav-link" %>
    <a class="nav-item nav-link" href="#"><i class='icon-account mdme-icon'></i> Account</a>
    <form class="pull-sm-right nav-item">
      <input type="text" class="form-control" placeholder="Search...">
    </form>
  </nav>
  <%= button_to "Sign Out".html_safe, signout_path, method: :delete, :class=>"nav-item nav-link btn btn-primary pull-xs-right", :id=>'admin-signout' %>


</nav>
<div class="row-fluid" style="margin-top: 1em;">
  <div class="col-md-10 col-md-offset-1">
    <div id="flash">
      <%= render 'shared/flash' %>
    </div>
  </div>
</div>

app/views/admins/_header_no_links.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <div class="breadcrumbs">
        <%= render_breadcrumbs  separator: ' > ' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3" style="text-align: center;">
      <%= link_to image_tag(asset_path('full_logo_white.png'), class: 'logo img-responsive'), root_path %>

    </div>
  </div>
</div>

app/views/admins/_header_old.html.erb
<div class="container-fluid">
  <%= render 'shared/flash' %>
  <div class="row">
    <div class="col-md-3">
      <div class="breadcrumbs">
        <%= render_breadcrumbs  separator: ' > ' %>
      </div>
    </div>
    <div class="col-md-3 col-md-offset-6" style="text-align: right;">
      <%= link_to 'Sign Out', session_path(current_admin), method: :delete %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3" style="text-align: center;">
      <%= link_to image_tag(asset_path('full_logo_white.png'), class: 'logo img-responsive'), root_path %>

    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <hr id="menu-topbar-black"/>
    </div>
  </div>
  <div class="row" style="margin-bottom: 9em;">
    <div class="col-md-10 col-md-offset-1">
      <div class="row top-links home-menu-links">
        <div class="col-xs-2 col-md-2 col-xs-offset-1 col-md-offset-1 <%= 'top-links-active' if @active == :appointments %>">
          <%= link_to 'APPOINTMENTS', admin_appointments_path(current_admin) %>
        </div>
        <div class="col-xs-2 col-md-2 <%= 'top-links-active' if @active == :doctors %>">
          <%= link_to 'DOCTORS', admin_doctors_path(current_admin) %>
        </div>
        <div class="col-xs-2 col-md-2 <%= 'top-links-active' if @active == :patients %>">
          <%= link_to 'PATIENTS', admin_patients_browse_path(current_admin) %>
        </div>
        <div class="col-xs-2 col-md-2 <%= 'top-links-active' if @active == :departments %>">
          <%= link_to 'DEPARTMENTS', admin_departments_path(current_admin) %>
        </div>
         <div class="col-xs-2 col-md-xs-2 <%= 'top-links-active' if @active == :administration %>">
           <%= link_to 'ADMINISTRATION', admin_clinic_path(current_admin, current_admin.clinic.id) %>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="<%='active' if @manage_appts_page %> %>"><%= link_to "<i class='icon-book mdme-icon'></i> Appointments".html_safe, admin_appointments_path(current_admin) %></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><%= link_to "<i class='fa fa-user-md'></i> Doctors".html_safe, admin_doctors_path(current_admin) %></li>
    <li><%= link_to "<i class='fa fa-users'></i> Patients".html_safe, admin_patients_path(current_admin) %></li>
    <li><%= link_to "<i class='fa fa-th-large'></i> Departments".html_safe, admin_departments_path(current_admin) %> </li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="#">Account Settings</a></li>
    <li><%= link_to "<i class='fa fa-minus-circle'></i> Sign Out".html_safe, signout_path, method: :delete %></li>
  </ul>
</div>

app/views/admins/_sidebar_old.html.erb
<div class="container-non-responsive" id="main-content">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <!-- upper section -->
  <div class="row">
    <div class="col-xs-3">
      <div class='panel panel-default'>
        <div class="panel-heading"><strong><i class="fa fa-medkit"></i> Toolbox</strong></div>
        <div class="well">

          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to "<i class='fa fa-calendar-o'></i> Today's Appointments".html_safe, admins_path %></li>
            <li><%= link_to "<i class='fa fa-book'></i> Manage Appointments".html_safe, admin_appointments_path(current_admin) %></li>
            <li><%= link_to "<i class='fa fa-user-md'></i> Manage Doctors".html_safe, admin_doctors_path(current_admin) %></li>
            <li><%= link_to "<i class='fa fa-users'></i> Manage Patients".html_safe, admin_patients_path(current_admin) %></li>
            <li></li>
            <li><%= link_to "<i class='fa fa-minus-circle'></i> Sign Out".html_safe, signout_path, method: :delete %></li>
          </ul>


      </div>
    </div>
  </div>

app/views/admins/index.html.erb
<h1 class="page-header">Dashboard</h1>

<div class="row placeholders">
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-fluid" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-fluid" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-fluid" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-fluid" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
</div>

<h2>Section title</h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>#</th>
      <th>Header</th>
      <th>Header</th>
      <th>Header</th>
      <th>Header</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>1,001</td>
      <td>Lorem</td>
      <td>ipsum</td>
      <td>dolor</td>
      <td>sit</td>
    </tr>
    <tr>
      <td>1,002</td>
      <td>amet</td>
      <td>consectetur</td>
      <td>adipiscing</td>
      <td>elit</td>
    </tr>
    <tr>
      <td>1,003</td>
      <td>Integer</td>
      <td>nec</td>
      <td>odio</td>
      <td>Praesent</td>
    </tr>
    <tr>
      <td>1,003</td>
      <td>libero</td>
      <td>Sed</td>
      <td>cursus</td>
      <td>ante</td>
    </tr>
    <tr>
      <td>1,004</td>
      <td>dapibus</td>
      <td>diam</td>
      <td>Sed</td>
      <td>nisi</td>
    </tr>
    <tr>
      <td>1,005</td>
      <td>Nulla</td>
      <td>quis</td>
      <td>sem</td>
      <td>at</td>
    </tr>
    <tr>
      <td>1,006</td>
      <td>nibh</td>
      <td>elementum</td>
      <td>imperdiet</td>
      <td>Duis</td>
    </tr>
    <tr>
      <td>1,007</td>
      <td>sagittis</td>
      <td>ipsum</td>
      <td>Praesent</td>
      <td>mauris</td>
    </tr>
    <tr>
      <td>1,008</td>
      <td>Fusce</td>
      <td>nec</td>
      <td>tellus</td>
      <td>sed</td>
    </tr>
    <tr>
      <td>1,009</td>
      <td>augue</td>
      <td>semper</td>
      <td>porta</td>
      <td>Mauris</td>
    </tr>
    <tr>
      <td>1,010</td>
      <td>massa</td>
      <td>Vestibulum</td>
      <td>lacinia</td>
      <td>arcu</td>
    </tr>
    <tr>
      <td>1,011</td>
      <td>eget</td>
      <td>nulla</td>
      <td>Class</td>
      <td>aptent</td>
    </tr>
    <tr>
      <td>1,012</td>
      <td>taciti</td>
      <td>sociosqu</td>
      <td>ad</td>
      <td>litora</td>
    </tr>
    <tr>
      <td>1,013</td>
      <td>torquent</td>
      <td>per</td>
      <td>conubia</td>
      <td>nostra</td>
    </tr>
    <tr>
      <td>1,014</td>
      <td>per</td>
      <td>inceptos</td>
      <td>himenaeos</td>
      <td>Curabitur</td>
    </tr>
    <tr>
      <td>1,015</td>
      <td>sodales</td>
      <td>ligula</td>
      <td>in</td>
      <td>libero</td>
    </tr>
    </tbody>
  </table>
</div>

app/views/admins/index_old.html.erb
<%= provide(:title, 'Admin Panel') %>
<%= render 'admins/header' %>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading"><h4>Today's Appointments</h4></div>
          <div class="panel-body panel-inverse">
            <div class="day_appointments">
            <%= render 'admins/appointments/appointments_table' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/patient_show.html.erb
<%= provide(:title, 'Patients') %>
<%= render 'admins/sidebar' %>

<%= render 'patients/shared_show' %>>


</div>

app/views/admins/show.html.erb
<%= render 'admins/sidebar' %>

<div class="col-md-30">
  <div class="row">
    <div class="col-md-7">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Today's Appointments</h4></div>
      <div class="panel-body">

        <table class='table table-striped table-bordered table-condensed'>
          <thread>
            <tr>
              <th>#</th>
              <th>Time</th>
              <th>Doctor</th>
              <th>Patient</th>
            </tr>
            <tbody>
              <% @appointments.each_with_index do |appointment, index| %>
              <tr>
                <td><%= index %></td>
                <td><%= appointment.appointment_time %></td>
                <td><%= full_name(Doctor.find(appointment.doctor_id)) %></td>
                <td><%= full_name(Patient.find(appointment.patient_id)) %></td>
              </tr>
              <% end %>
            </tbody>
          </thread>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
</div>