config/routes.rb
MDme::Application.routes.draw do
  require 'domains'

  match '/', to: 'doctors#signin', via: 'get', constraints: { subdomain: 'doctors' }

  match '/',     to: 'admins#signin', via: 'get',    constraints: { subdomain: 'admin' }
  match '/', to: 'static_pages#home', via: 'get'
  root 'static_pages#home', constraints: { subdomain: 'www' }

  match '/help',            to: 'static_pages#help',     via: 'get'#,    constraints: { subdomain: 'www' }
  match '/about',           to: 'static_pages#about',    via: 'get'#,    constraints: { subdomain: 'www' }
  match '/contact',         to: 'static_pages#contact',  via: 'get'#,    constraints: { subdomain: 'www' }
  match '/signin',          to: 'sessions#new',          via: 'get'#,    constraints: { subdomain: 'www' }
  match '/signout',         to: 'sessions#destroy',      via: 'delete'
  match '/forgot_password', to: 'password_reset#new',    via: 'get',    as: :forgot_password
  match '/forgot_password', to: 'password_reset#create', via: 'post',   as: :password_reset

  post '/submit-comment'                                 => 'static_pages#submit_comment',             as: :contact_comment_path
  post 'appointments/check-in'                           => 'admins/appointments#check-in',            as: :admin_appointment_check_in
  get  'patients/:patiend_id/appointments/browse'        => 'patients/appointments#open_appointments', as: :open_appointments_browse
  get  'patients/:patient_id/appointments/requests'      => 'patients/appointments#open_requests',     as: :open_requests

  get  'admins/:admin_id/doctors/search'                 => 'admins/doctors#search',                   as: :admin_doctors_search
  get  'admins/:admin_id/patients/search'                => 'admins/patients#search',                  as: :admin_patient_search
  get  'admins/:admin_id/patients/browse'                => 'admins/patients#browse',                  as: :admin_patients_browse
  get  'admins/:admin_id/patients/:id/registration-form' => 'admins/patients#registration_form',       as: :admin_patient_registration_form
  get  'admins/:admin_id/appointments/browse'            => 'admins/appointments#browse',              as: :admin_appointments_browse
  get  'admins/:admin_id/appointments/ajax-browse'       => 'admins/appointments#ajax_browse',         as: :appointments_ajax_browse
  get  'admins/:admin_id/appointments/new/browse'        => 'admins/appointments#new_browse',          as: :admin_open_appointments_browse
  post 'admins/:admin_id/appointments/notify_ready'      => 'admins/appointments#notify_ready',        as: :notify_appointment_ready
  get  'admins/:admin_id/doctors/opentimes'              => 'admins/doctors#open_times',               as: :admin_doctors_opentimes
  get  'patients/:admin_id/doctors/opentimes'            => 'patients/appointments#open_times',        as: :patients_doctors_opentimes
  get  'doctors/opentimes'                               => 'doctors#open_appointments',               as: :doctor_open_appointments
  get  'doctors/:id/public'                              => 'doctors#show_public',                     as: :doctor_public_show
  get  'doctors/:id/changepassword'                      => 'doctors#change_password',                 as: :doctor_password
  post 'doctors/:id/updatepassword'                      => 'doctors#update_password',                 as: :doctor_update_password

  get 'clinics/:id/checkin/:patient_id'                  => 'clinics#checkin',                         as: :clinic_checkin

  get 'appointments/:id/fill_appointment'                => 'appointments#fill_appointment',           as: :fill_appointment

  resources :sessions, only: [:new, :create, :destroy]
  resources :admins, only: [:index]
  resources :doctors, except: [:new, :create, :destroy]

  resources :doctors do
    resources :appointments, only: [:index, :show], controller: 'doctors/appointments'
    resources :patients,     only: [:index, :show], controller: 'doctors/patients'
  end

  resources :patients do
    resources :appointments, controller: 'patients/appointments' do
      collection do
        get :home
      end
    end
    resources :doctors, only: [:index, :show], controller: 'patients/doctors'
    resources :clinics, only: [:index, :show], controller: 'patients/clinics' do
      collection do
        post :open_times
        get :get_doctors
      end
      member do
        get :display
      end
    end
    resources :devices, only: [:create],       controller: 'patients/devices'
    member do
      get   :change_password
      patch :update_password
    end
    collection do
      get :get_upcoming_appointment
    end
  end

  resources :clinics do
    resources :doctors, only: [:index], controller: 'clinics/doctors'
  end
  
  resources :admins do
    resources :departments,  controller: 'admins/departments'
    resources :patients,     controller: 'admins/patients'
    resources :doctors,      controller: 'admins/doctors'
    resources :appointments, controller: 'admins/appointments' do
      collection do
        get  :approval
        get  :show_on_date
        get  :manage_delays
      end
      member do
        post :approve_deny
        post :add_delay
      end
    end
    resources :clinics,      controller: 'admins/clinics'  do
      collection do
        post :open_times
      end
    end
  end

  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
      resources :patients, controller: 'patients', only: [:index]
      get 'patients/show' => 'patients#show', as: 'patient_profile'
      put 'patients/update' => 'patients#update', as: 'patient_update_profile'

      namespace :patients do
        get 'appointments/confirmed' => 'appointments#confirmed_appointments', as: 'confirmed_appointments'
        get 'appointments/requested' => 'appointments#requested_appointments', as: 'requested_appointments'
        resources :doctors, controller: 'doctors', only: [:index, :show]
        resources :appointments, controller: 'appointments', only: [:create, :update, :show, :index]
        resources :clinics, controller: 'clinics', only: [:index, :show]
        resources :devices, controller: 'devices', only: [:create]
        get 'departments' => 'doctors#department_index', as: 'doctors_departments'

      end
    end
    namespace :mobile do
      get  'patients/:patient_id/upcoming-appointment-qrcode'=> 'patients#upcoming_appointment_qrcode',     as: :upcoming_appointment_qrcode
      post 'login' => 'sessions#create'
      delete 'sessions' => 'sessions#destroy'
      get  'patients/get-upcoming-appointment' => 'patients#get_upcoming_appointment'
      resources :patients, controller: 'patients', only: [:show, :edit, :update, :destroy]
      namespace :patients do
        resources :devices, controller: 'devices', only: [:create]
      end
    end
  end

  

end

app/controllers/admins/appointments_controller.rb
# MDme Rails master application
# Author:: Matt Hamada (maito:mattahamada@gmail.com)
# 3/2914
# Copyright:: Copyright (c) 2014 MDme
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential.

# <tt>Admins::AppointmentsController</tt>
# for admin.mdme.us/admins/:admin_id/appointments
class Admins::AppointmentsController < Admins::ApplicationController

  # before_filter :find_admin
  # before_filter :require_admin_login
  # before_filter :set_active_navbar
  # before_action :authenticate_admin_header
  before_filter :require_admin_login
  before_action :check_appointments_needing_approval
  # GET admin.mdme.us/admins/:admin_id/appointments
  def index
    @manage_appts_page = true
    @find_appointments_page = true
    if params[:date].present?
      @doctors = Doctor.where(:id=>Appointment.in_clinic(@admin).given_date(Date.strptime(params[:date],"%m/%d/%Y")).confirmed.pluck(:doctor_id).uniq)
      if params[:doctor_id]
        @appointments = @doctors.where(:id=>params[:doctor_id]).first.appointments_on_date(Date.strptime(params[:date],"%m/%d/%Y")).includes(:patient) rescue []
      else
        @appointments = @doctors.first.appointments_on_date(Date.strptime(params[:date],"%m/%d/%Y")).includes(:patient) rescue []
      end
    else
      # @doctors = Doctor.where(:id=>Appointment.in_clinic(@admin).today.confirmed.pluck(:doctor_id).uniq)
      @doctors = Doctor.in_clinic(@admin).with_appointments_today.order("last_name")
      if params[:doctor_id]
        @appointments = @doctors.find(params[:doctor_id]).appointments_today.includes(:patient) rescue []
      else
        @appointments = @doctors.first.appointments_today.includes(:patient) rescue []
      end
    end
    if request.xhr?
      return render :partial=> 'appointments_table', :layout=>false
    end
  end

  # Shows a list of appointments occurring today for setting delays
  # GET admin.mdme.us/admins/:admin_id/appointments/manage_delays
  def manage_delays
    @appointment_delays_page = true
    @doctors = Doctor.in_clinic(@admin).with_appointments_today.order("last_name")
    if params[:doctor_id]
      @appointments = @doctors.find(params[:doctor_id]).appointments_today.includes(:patient) rescue []
    else
      @appointments = @doctors.first.appointments_today.includes(:patient) rescue []
    end
    if request.xhr?
      return render :partial=>'delay_table', :layout=>false
    end
  end

  # GET admin.mdme.us/admins/:admin_id/appointments/new
  def new
    @add_appointment_page = true
    @appointment = Appointment.new(appointment_time: DateTime.now, :clinic_id=>@admin.clinic_id)
    @doctors = @admin.clinic.doctors.order("last_name, first_name")
    @patients = @admin.clinic.patients.order("last_name, first_name")
    @open_times = []

  end

  # GET admin.mdme.us/admins/:admin_id/appointments/:id/edit
  def edit
    @appointment = appointment
    @open_times = @appointment.doctor.open_appointment_times(@appointment.appointment_time.to_date)
    # @open_times << @appointment.time_selector
    render status: 200, json: {open_times: @open_times}
  end

  # PATCH admin.mdme.us/admins/:admin_id/appointments/:id/
  def update
    @appointment = appointment
    input_params = appointment_params
    datetime = Time.zone.parse("#{@appointment.date} #{input_params[:time]}")
    if @appointment.update_attributes(appointment_time: datetime,
                                      description: input_params[:description])
      render status: 201, json: {status: "Appointment was successfully updated."}
    else
      flash.now[:danger] = "Invalid parameters in update"
      render status: 400, json: {status: @appointment.errors.full_messages}
    end
  end

  # DELETE admin.mdme.us/admins/:admin_id/appointments/:id/
  def destroy
    @appointment = appointment
    if @appointment.destroy
      flash[:warning] = "Appointment deleted"
      redirect_to admin_appointments_path(@admin)
    else
      flash.now[:danger] = "Error processing request"
      admin_appointment_path(@appointment)
    end

  end

  # Ajax load - For open appointments given selected doctor
  # GET admin.mdme.us/admins/:admin_id/appointments/new_browse
  def new_browse
    input = appointment_params
    @date = Date.parse(input[:date])
    @doctor = Doctor.find(input[:doctor_id])
    @open_times = @doctor.open_appointment_times(@date)
    @appointment = Appointment.new
  end

  # Ajax load - Shows all confirmed appointments on a given date for  index page
  # Expects the param :day passed as a string date to parse
  # GET admin.mdme.us/admins/:admin_id/appointments/browse
  def browse
    date = Date.parse(params[:date])
    # if date < Date.today
    #   flash[:danger] = 'Time must be set in the future'
    #   redirect_to admin_appointments_path(@admin)
    # else
      @appointments = Appointment.in_clinic(@admin).given_date(date).
          confirmed.order('appointment_time ASC').load.includes([:doctor,
                                                                 :patient])
    # end
  end

  # POST admin.mdme.us/admins/:admin_id/appointments
  def create
    input = appointment_params
    if input.has_key? :time
      time = input[:time]
      day = Date.strptime(input[:date], '%m/%d/%Y')
      date = Time.zone.parse("#{day.strftime('%F')} #{time}")
      @appointment = Appointment.new(doctor_id: input[:doctor_id],
                                     patient_id: input[:doctor_id],
                                     appointment_time: date,
                                     description: input[:description],
                                     status: 'confirmed',
                                     clinic_id: @admin.clinic_id,
                                     inform_earlier_time: input[:inform_earlier_time])
      if @appointment.save
        respond_to do |format|
          format.html do
            flash[:success] = "Appointment created"
            redirect_to admin_appointments_path(@admin)
          end
          format.json do
            render status: 201, json: {status: 'Appointment Created'}
          end
          format.js {}
        end
      else
        respond_to do |format|
          format.html do
            flash[:error] = "Error creating appointment"
            redirect_to new_admin_appointment_path(@admin)
          end
          format.json do
            render status: 400, json: {errors: @appointment.errors.full_messages}
          end
          format.js do
            @error = true
            @errors = @appointment.errors.full_messages.join("\n  ")
          end
        end
      end
    else
      respond_to do |format|
        format.json do
          render status: 400, json: {errors: ['No time selected']}
        end
        format.html do
          flash[:error] = "No time selected"
          redirect_to new_admin_appointment_path(@admin)
        end
        format.js {}
      end
    end

  end

  # Shows list of appointments awaiting approval
  # GET admin.mdme.us/admins/:admin_id/appointments/approval
  def approval
    @appointment_approval_page = true
    @appointments = Appointment.in_clinic(@admin).not_past.requests.order("appointment_time, created_at")
    @doctors = Doctor.where(:id=>@appointments.pluck(:doctor_id).uniq).order("last_name, first_name")
    if params[:doctor_id]
      @appointments = @appointments.includes(:patient).where(:doctor_id=>params[:doctor_id])
    elsif @doctors.any?
      @appointments = @appointments.includes(:patient).where(:doctor_id=>@doctors.first.id)
    end
    @approve_deny_column_set = true
    if request.xhr?
      return render :partial=>'approval_table', :layout=>false
    end
  end

  

  # Allows admin to see what appointments are already on a
  # specific date with a specific doctor before Accepting/denying request
  # GET admin.mdme.us/admins/:admin_id/appointments/show_on_date
  def show_on_date
    @date = Appointment.find(params[:appointment_id]).appointment_time.to_date
    @doctor = Doctor.find(params[:doctor_id]).full_name
    @appointments = Appointment.in_clinic(@admin).
        given_date(@date).confirmed.with_doctor(params[:doctor_id]).
        order('appointment_time ASC').load  
    @hide_table_checkin = true
    render(partial: 'ajax_show_on_date') if request.xhr?
  end

  # run when admin hits approve or deny on approval page
  # POST admin.mdme.us/admins/:admin_id/appointments
  def approve_deny
    @appointment = Appointment.find(params[:id])
    if params[:confirmed] != 'false'
      @appointment.confirm
      respond_to do |format|
        format.html do
          flash[:success] = 'Appointment Confirmed'
          redirect_to approval_admin_appointments_path(@admin, :doctor_id=>@appointment.doctor_id)
        end
        format.js do
          @confirmed = true
        end
        format.json do
          render status: 200, json: {
              status: :confirmed,
              message: 'Appointment confirmed'
          }
        end
      end
      
    else
      @appointment.deny
      respond_to do |format|
        format.html do
          flash[:warning] = 'Appointment Denied'
          redirect_to approval_admin_appointments_path(@admin, :doctor_id=>@appointment.doctor_id)
        end
        format.js do
          @confirmed = false
        end
        format.json do
          render status: 200, json: {
                status: :deleted,
              message: 'Appointment denied'
          }
        end
      end
      
    end
    # if params.has_key?(:approve)
    #   appointment.request = false
    #   appointment.save!
    #   appointment.email_confirmation_to_patient(:approve)
    # elsif params.has_key?(:deny)
    #   appointment.email_confirmation_to_patient(:deny)
    #   appointment.destroy
    # end
    # redirect_to appointment_approval_path(@admin.id)
  end

  # GET admin.mdme.us/admins/:admin_id/appointments/:id
  def show
    @appointment = appointment
    @doctor = @appointment.doctor

app/helpers/api/v1/patients/appointments_helper.rb
module Api::V1::Patients::AppointmentsHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/admins/appointments/_ajax_show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <%= render 'appointments/show' %>
    </div>
  </div>
</div>
</div>

app/views/admins/appointments/_approval_table.html.erb
<ul class="nav nav-tabs" data-turbolinks="false">
  <% @doctors.each_with_index do |doctor, index| %>
    <li data-id="<%= doctor.id %>" class="nav-item doc-tab">
      <a id="<%= doctor.id %>" class=" doc-tab-link nav-link <%= 'active' if (params[:doctor_id].nil? && index == 0) || params[:doctor_id] == doctor.id.to_s %>" href="#">
        <%= doctor.full_name %>
      </a>
    </li>
  <% end %>
</ul>

<table class='table table-striped table-bordered table-hover'>
  <thread>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Patient</th>
        <th>Options</th>
    </tr>
    <tbody>
    <% @appointments.each_with_index do |appointment, index| %>
      <tr id="<%= appointment.id %>" class="linked-no-url appointment-row" data-toggle="modal" data-target="#approval-popup">
        <td><%= appointment.date %><%# "#{appointment.date} (#{link_to 'See schedule', '#', :class=>'show-on-date', "data-toggle"=>"modal", 'data-target'=>"#approval-popup", 'data-doctorid'=>appointment.doctor_id, 'data-id'=>appointment.id })".html_safe %></td>
        <td><%= appointment.time_am_pm %></td>
        <td><%= appointment.patient_full_name %></td>
        <td style="text-align: center;">
          <%= link_to 'Approve', approve_deny_admin_appointment_path(@admin, appointment, confirmed: true),method: :post, class: 'btn btn-mini btn-success approve' %>
          <%= link_to 'Deny', approve_deny_admin_appointment_path(@admin, appointment, confirmed: false), method: :post, class: 'btn btn-mini btn-danger deny' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </thread>
</table>

<div class="modal" id="approval-popup" tabindex="-1" role="dialog"
     aria-labelledby="approval-popup" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="popup-title"></h4>
      </div>
      <div class="modal-body" id="popup-content">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('.appointment-row').on('click', function() {
      appointment_id = $(this).attr('id');
      $.ajax({
        method: 'get',
        url: '/admins/<%=@admin.id%>/appointments/' + appointment_id,
        success: function(data) {
          $('#popup-content').html(data);
          $('#popup-title').html('');
        }
      })
    });
    $('.show-on-date').on('click', function() {
      appointment_id = $(this).data('id');
      doctor_id = $(this).data('doctorid');
      $.ajax({
        method: 'get',
        url: '<%= show_on_date_admin_appointments_path(@admin) %>',
        data: {appointment_id: appointment_id, doctor_id: doctor_id},
        success: function(data) {
          $('#popup-content').html(data);
          $('#popup-title').html($('#use-for-title').html());
        }
      });
      return false;
    });
    $('li.doc-tab').on('click', function() {
      doctor_id = $(this).data('id');
      var date  = $('input#date').val();
      $.ajax({
        method: 'get',
        url: '<%= request.path %>',
        data: { doctor_id: doctor_id, date: date },
        success: function(data) {
          $('#appointments-list').html(data);
        },
        complete: function() {
          $('a.doc-tab-link').attr('class', 'nav-link doc-tab-link');
          $('a#' + doctor_id).attr('class', 'nav-link doc-tab-link active');
          $('#flash').html('');
        }
      });
    });
  })
</script>

app/views/admins/appointments/_days_appointments.html.erb
<%= render 'appointments_table' %>

app/views/admins/appointments/ajax_browse.js.erb
$(".day_appointments").html("<%= escape_javascript(render('days_appointments', appointments: @appointments)) %>");

app/views/admins/appointments/browse.html.erb
<%= provide(:title, " | Browse Appointments") %>
<%= render 'admins/header' %>

<div class="row">
  <div class="col-md-5 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Select Date</h4></div>
      <div class="panel-body panel-inverse">

        <%= form_for(:appointment, url:appointments_ajax_browse_path, remote: true, method: :get, html: { class: 'form-group form-inline', role: 'form' }) do |f| %>
          <div class="form-group">
            <%= f.label(:day, "Select Date") %>
          </div>
          <div class="form-group">
            <%= f.text_field(:day, class: "form-control" ) %>
          </div>
          <div class='form-group' id="submit">
            <%= f.submit 'Submit' , class: 'btn btn-large btn-primary', id: 'submit_button' %>
          </div>
        <% end %>
      </div>
      <div class='day_appointments'>

      </div>
    </div>
  </div>



  <div class="col-md-3">
    <div class="row">
      <div class="col-md-12 inverse-color">
        <%= link_to "Browse Appointments", admin_appointments_browse_path(@admin) %><br/>
        <%= link_to "Add Appointment", new_admin_appointment_path(@admin) %><br/>
        <%= link_to "Appointment Requests", appointment_approval_path(@admin) %> <br/>
        <%= link_to "Manage Delays", manage_delays_path(@admin) %>  <br/>
      </div>
    </div>
  </div>
</div>

app/views/admins/appointments/create.js.erb
<% if @error %>
  var errorDiv = $(document.createElement('div'));
  errorDiv.addClass('appointment-errors alert alert-danger');
  errorDiv.html('<%=@errors%>');
  $('.modal-header').append(errorDiv);
<% else %>
  $('#appointment-request-modal').modal('hide');
  $('#flash').addClass('alert alert-success').html(
      'Appointment Requested'
  );
  $('#date_time_slots').html('');
  window.scrollTo(0, 0);
<% end %>

app/views/admins/appointments/manage_delays.html.erb
<%= provide(:title, "Manage Delays | ") %>

<div class="container-fluid">
  <%= render 'admins/appointments/sub_menu.html.erb' %>
  <div id="appointments-list" style="margin-top: 1em;">
    <%= render 'delay_table' %>
  </div>
</div>

app/views/admins/appointments/new.html.erb
<%= provide(:title, "New Appointment |") %>
<%= render 'admins/appointments/sub_menu.html.erb' %>
<div class="container-fluid" style="background-color: #f5f5f5; padding-top: 2em; padding-bottom: 2em;">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_tag open_times_admin_clinics_path(@admin), :remote=>true, :id=>'open-times-form' do %>
        <fieldset class="form-group row">
          <label for="appointment_doctor_id" class="col-sm-3 form-control-label"><small>Provider:</small></label>
          <div class="col-sm-9">
            <%= select :appointment, :doctor_id, options_from_collection_for_select(@doctors, :id, :full_name), {:prompt => "--Select Doctor--"}, {:class=>'form-control'}  %>
          </div>
        </fieldset>
        <fieldset class="form-group row">
          <label for="appointment_patient_id" class="col-sm-3 form-control-label"><small>Patient:</small></label>
          <div class="col-sm-9">
            <%= select :appointment, :patient_id, options_from_collection_for_select(@patients, :id, :full_name, :selected=>params[:patient_id]), {:prompt => "--Select Patient--"}, {:class=>'form-control'}  %>
          </div>
        </fieldset>
        <fieldset class="form-group row">
          <label for="appointment_date" class="col-sm-3 form-control-label"><small>Date:</small></label>
          <div class="col-sm-9">
            <%= text_field_tag 'date', '', :class=>'date-pick form-control' %>
          </div>
        </fieldset>
        <fieldset class="form-group row">
          <label for="appointment_time_of_day" class="col-sm-3 form-control-label" style="white-space: nowrap;"><small>Time of Day:</small></label>
          <div class="col-sm-9">
            <%= select_tag :time_of_day, options_for_select(['All', 'Morning', 'Afternoon'], :selected=>'All'), :class=>'form-control' %>
          </div>
        </fieldset>
        <fieldset class="form-group" style="text-align: center; margin-top: 1em;">
          <%# hidden_field_tag :day_start %>
          <%# hidden_field_tag :day_end %>

          <%= submit_tag 'Search', :class=>'btn btn-primary' %>
        </fieldset>
      <% end %>
    </div>
  </div>
  <div id="date_time_slots"></div>
  <hr/>
</div>
<div class="modal fade" id="appointment-request-modal" tabindex="-1" role="dialog" aria-labelledby="appointment-form-popup" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="appointment-form-popup"></h4>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1" id="appointment-modal-provider">
              Provider:
            </div>
          </div>
          <hr/>
          <div class="row">
            <div class="col-sm-12" data-turbolinks="false">
              <%= form_for @appointment, url: url_for(controller: 'admins/appointments', action: 'create', :admin_id=>@admin.id), :remote=>true, :html=>{:id=>'appointment-request-form'} do |f| %>
                <%= hidden_field_tag 'appointment[date]' %>
                <%= hidden_field_tag 'appointment[time]' %>
                <%= hidden_field_tag 'appointment[doctor_id]' %>
                <%= hidden_field_tag 'appointment[patient_id]' %>
                <fieldset class="form-group row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <label for="appointment_description">Reason for visit:</label>
                    <%= f.text_area :description, :class=>'form-control', :rows=>'6' %>
                  </div>
                </fieldset>
                <fieldset class="checkbox row">
                  <div class="col-sm-10 col-sm-offset-1">
                    <%= f.check_box :inform_earlier_time %>  Inform patient if earlier time slot opens
                  </div>
                </fieldset>
                </div>
                </div>
                </div>
                </div>
                <div class="modal-footer">
                  <div style="text-align: center;">
                    <%= f.submit 'Request', :class=>'btn btn-primary' %>
                  </div>
                </div>
              <% end %>
              </div>
  </div>
</div>


<script type="text/javascript">

  $(document).on('click', '.time-slot-button', function() {
    var openTimesForm = $('#open-times-form');
    var modalWrapper = $('#appointment-request-modal');
    var date = new Date(openTimesForm.find('input#date').val());
    switch ($(this).data('dateslot')) {
      case 0:
        date = new Date(date.setDate(date.getDate()-1));
        break;
      case 2:
        date = new Date(date.setDate(date.getDate()+1));
        break;
    }
    var dateText = $(this).parent().parent().parent().parent().find('.date-slot small').text();
    var time = $(this).text();
    modalWrapper.find('input#appointment_time').val(time);
    modalWrapper.find('input#appointment_date').val("" + (1+date.getMonth()) + '/' + date.getDate() + '/' + date.getFullYear());
    modalWrapper.find('input#appointment_doctor_id').val(openTimesForm.find('select#appointment_doctor_id').val());
    modalWrapper.find('input#appointment_patient_id').val(openTimesForm.find('select#appointment_patient_id').val());
    modalWrapper.find('#appointment-modal-provider').html('Provider: ' + openTimesForm.find('select#appointment_doctor_id option:selected').text());
    modalWrapper.find('.modal-title').html(dateText + ' ' + time);
  });

  $('#appointment-request-modal').on('hidden.bs.modal', function() {
    $('.appointment-errors').remove();
  });
</script>